name: Python Microservice Application

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Git Repo
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.6
      - name: Install dependencies
        run: |
          make install
      - name: Format code
        run: |
          make format
      - name: Lint with pylint
        run: |
          make lint
      - name: Test with pytest
        run: |
          make test
  
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Pull Git Repo
        uses: actions/checkout@v2
      - name: Build Container
        run: |
          make build
